# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingtype',
            name='type_classification',
            field=models.CharField(choices=[('UN', 'Unknown'), ('JC', 'Jacket/Coat'), ('UO', 'Upper Body - Outer'), ('UI', 'Upper Body - Inner'), ('LB', 'Lower Body'), ('SO', 'Socks'), ('SH', 'Shoes'), ('HC', 'Hat - Cold_Weather'), ('HA', 'Hat - All_Purpose'), ('SC', 'Scarf'), ('GL', 'Gloves')], default='Unknown', max_length=2, null=True),
        ),
    ]
