# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 00:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0002_clothingtype_type_classification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='weather_type',
            field=models.CharField(choices=[('Y', 'Sunny'), ('S', 'Snowy'), ('R', 'Rainy'), ('C', 'Cloudy'), ('H', 'Hurricane'), ('I', 'Hail'), ('T', 'Thunder'), ('P', 'Partly Cloudy'), ('M', 'Chance of Meatballs'), ('O', 'Tornado')], default='Partly Cloudy', max_length=1),
        ),
    ]
