# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 00:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0003_auto_20171202_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(help_text='Enter a clothing type (Shirt, Pants, etc.)', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycloset.WeatherType'),
        ),
    ]
