# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0004_auto_20171202_1929'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='weather',
        ),
        migrations.RemoveField(
            model_name='clothingtype',
            name='type_classification',
        ),
        migrations.AlterField(
            model_name='clothingtype',
            name='type_name',
            field=models.CharField(help_text='Enter a clothing classification', max_length=200),
        ),
    ]
