# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 01:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0006_weathertype_clothing_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='weather_type',
        ),
    ]
