# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-03 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0007_remove_weather_weather_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='weather_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycloset.WeatherType'),
        ),
    ]
