# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0011_auto_20171206_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathersuggestion',
            name='suggestion_name',
            field=models.CharField(default='Not Used', help_text='Enter the name for this weather suggestion', max_length=100),
        ),
    ]
