# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-07 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0012_weathersuggestion_suggestion_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='favorite',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='weathersuggestion',
            name='clothing_types',
            field=models.ManyToManyField(help_text='Select the (non-shoe) clothing types to be worn for this type of weather', to='mycloset.ClothingType'),
        ),
    ]
