# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0015_auto_20171207_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='weather_type',
        ),
        migrations.RemoveField(
            model_name='weathertype',
            name='clothing_types',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
        migrations.DeleteModel(
            name='WeatherType',
        ),
    ]
