# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-28 03:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clothing',
            fields=[
                ('clothing_name', models.CharField(default='', help_text='Enter clothing name (e.g. Dark Wash Jeans)', max_length=200)),
                ('clothing_picture', models.CharField(help_text='Enter the url for your desired image', max_length=200, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular clothing across whole closet', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(help_text='Enter a clothing type (Shirt, Pants, etc.)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular clothing across whole closet', primary_key=True, serialize=False)),
                ('favorite', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='No', max_length=1)),
                ('outfit_name', models.CharField(help_text='Enter outfit name', max_length=200)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('clothing', models.ManyToManyField(help_text='Select all clothing for your outfit', to='mycloset.Clothing')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.CharField(help_text='Enter the url for your desired image', max_length=200, null=True)),
                ('description', models.TextField(help_text='Enter a description for your profile', max_length=1000, null=True)),
                ('phone', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('gender', models.CharField(default='', help_text='Please Input F (Female), M (Male), or O (Other)', max_length=1, verbose_name='Gender')),
                ('residence', models.CharField(default='', help_text='Enter your location of residence', max_length=200, verbose_name='Residence')),
                ('closet', models.ManyToManyField(help_text='Select clothing for closet', to='mycloset.Clothing')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_type', models.CharField(max_length=20)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='outfit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycloset.Outfit'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clothing',
            name='clothing_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycloset.ClothingType'),
        ),
        migrations.AddField(
            model_name='clothing',
            name='weather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycloset.Weather'),
        ),
    ]
