# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0002_auto_20171122_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(help_text='Enter a description for your profile', max_length=1000, null=True),
        ),
    ]
