# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0002_auto_20171027_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='author',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='summary',
        ),
        migrations.DeleteModel(
            name='Outfit',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
    ]
