# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0007_auto_20171027_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contactInfo',
            field=models.TextField(default='', help_text='Enter your email address', max_length=1000, verbose_name='Contact Info'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', help_text='Please Input F (Female), M (Male), or O (Other)', max_length=1, verbose_name='Gender'),
        ),
    ]
