# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0008_auto_20171027_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='closet',
            field=models.ManyToManyField(help_text='Select clothing for closet', to='mycloset.Clothing'),
        ),
    ]
