# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 20:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0009_user_closet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleComment', models.TextField(max_length=2000)),
            ],
        ),
        migrations.AddField(
            model_name='outfit',
            name='userComment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycloset.Comments'),
        ),
    ]
