# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0010_auto_20171027_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_type', models.TextField(max_length=20)),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
            ],
        ),
        migrations.RenameField(
            model_name='outfit',
            old_name='OutfitName',
            new_name='outfit_name',
        ),
        migrations.RenameField(
            model_name='outfit',
            old_name='userComment',
            new_name='user_comment',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contactInfo',
            new_name='contact_info',
        ),
    ]
