# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0011_auto_20171027_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='singleComment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='outfit',
            name='user_comment',
        ),
        migrations.AddField(
            model_name='clothing',
            name='weather',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycloset.Weather'),
        ),
        migrations.AddField(
            model_name='comments',
            name='outfit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycloset.Outfit'),
        ),
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycloset.User'),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='clothing_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mycloset.ClothingType'),
        ),
    ]
