# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0012_auto_20171030_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothingtype',
            old_name='name',
            new_name='type_name',
        ),
        migrations.AddField(
            model_name='clothing',
            name='clothing_name',
            field=models.CharField(default='', help_text='Enter clothing name (e.g. Dark Wash Jeans)', max_length=200),
        ),
    ]
