# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0015_auto_20171030_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='weather_type',
            field=models.CharField(max_length=20),
        ),
    ]
