# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-30 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0016_auto_20171030_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothingtype',
            name='type_name',
            field=models.CharField(help_text='Enter a clothing type (Shirt, Pants, etc.)', max_length=200),
        ),
    ]
