# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0018_clothing_clothing_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='clothing_image',
        ),
    ]
