# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0020_clothing_clothing_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.CharField(help_text='Enter the url for your desired image', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='clothing_picture',
            field=models.CharField(help_text='Enter the url for your desired image', max_length=200),
        ),
    ]
