# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0021_auto_20171031_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='clothing_picture',
            field=models.CharField(help_text='Enter the url for your desired image', max_length=200, null=True),
        ),
    ]
