# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 01:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycloset', '0022_auto_20171031_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='favorite',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='No', max_length=1),
        ),
        migrations.AddField(
            model_name='outfit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mycloset.User'),
        ),
        migrations.AddField(
            model_name='user',
            name='residence',
            field=models.CharField(default='', help_text='Enter your location of residence', max_length=200, verbose_name='Residence'),
        ),
    ]
